export const actionTypes = {
  FETCH_ACTUAL_STATUS_COMPLETED: 'FETCH_ACTUAL_STATUS_COMPLETED',
  FETCH_ACTUAL_STATUS_FAILED: 'FETCH_ACTUAL_STATUS_FAILED',
  FETCH_ACTUAL_STATUS_REQUEST: 'FETCH_ACTUAL_STATUS_REQUEST',
};